package com.github.theoakemontrainers.oakedex.dblookups;

public class Statements {
  public static final String ENGLISH_NAME = "select"
      + "   language_names.name as \"language\","
      + "   pokemon_species_names.name AS \"species name\","
      + "   pokemon_form_names.form_name AS \"form name\""
      + " from pokemon_species_names"
      + "   join pokemon on pokemon_species_names.pokemon_species_id = pokemon.species_id"
      + "   join pokemon_forms on pokemon.id = pokemon_forms.pokemon_id"
      + "   join pokemon_form_names on pokemon_forms.id = pokemon_form_names.pokemon_form_id"
      + "     and pokemon_species_names.local_language_id = pokemon_form_names.local_language_id"
      + "   join language_names on pokemon_form_names.local_language_id = language_names.language_id"
      + "     and language_names.local_language_id = 9"
      + " where pokemon_forms.id = ?;";
  
  public static final String ALL_NAMES = "select"
      + "   language_names.name as \"language\","
      + "   pokemon_species_names.name AS \"species name\","
      + "   pokemon_form_names.form_name AS \"form name\""
      + " from pokemon_species_names"
      + "   join pokemon on pokemon_species_names.pokemon_species_id = pokemon.species_id"
      + "   join pokemon_forms on pokemon.id = pokemon_forms.pokemon_id"
      + "   join pokemon_form_names on pokemon_forms.id = pokemon_form_names.pokemon_form_id"
      + "     and pokemon_species_names.local_language_id = pokemon_form_names.local_language_id"
      + "   join language_names on pokemon_form_names.local_language_id = language_names.language_id"
      + "     and language_names.local_language_id = 9"
      + " where pokemon_forms.id = ?;";
  
  public static final String MAIN_INFO = "SELECT"
      + "  spec.id AS \"number\"," + "  t1n.name AS \"type 1\","
      + "  t2n.name AS \"type 2\"," + "  a1n.name AS \"ability 1\","
      + "  a2n.name AS \"ability 2\","
      + "  a3n.name AS \"hidden ability\","
      + "  spec.gender_rate AS \"gender ratio\","
      + "  spec.generation_id AS \"generation\""
      + "FROM pokemon_species AS spec" + "  JOIN pokemon AS pkmn"
      + "    ON spec.id = pkmn.species_id" + "  JOIN pokemon_forms AS form"
      + "    ON pkmn.id = form.pokemon_id" + "  JOIN pokemon_types AS ptyp"
      + "    ON pkmn.id = ptyp.pokemon_id" + "  JOIN type_names AS t1n"
      + "    ON ptyp.type_id_1 = t1n.type_id"
      + "      AND t1n.local_language_id = 9"
      + "  LEFT JOIN type_names AS t2n"
      + "    ON ptyp.type_id_2 = t2n.type_id"
      + "      AND t2n.local_language_id = 9"
      + "  JOIN pokemon_abilities AS pabi"
      + "    ON pkmn.id = pabi.pokemon_id" + "  JOIN ability_names AS a1n"
      + "    ON pabi.ability_id_1 = a1n.ability_id"
      + "      AND a1n.local_language_id = 9"
      + "  LEFT JOIN ability_names AS a2n"
      + "    ON pabi.ability_id_2 = a2n.ability_id"
      + "      AND a2n.local_language_id = 9"
      + "  LEFT JOIN ability_names AS a3n"
      + "    ON pabi.hidden_ability_id = a3n.ability_id"
      + "      AND a3n.local_language_id = 9" + "WHERE form.id = ?";
}
